PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE services (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL,
  price_cents INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active'
, sub_category TEXT NOT NULL DEFAULT 'General');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-haircut','Haircut','Hair',30,4500,'Active','Cuts');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-colour','Colour service','Hair',90,12000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment','Hair treatment','Hair',45,7000,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-blowdry','Blow dry','Hair',35,5500,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial','Beauty facial','Beauty',60,9500,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading','Eye Brow Threading','Threading',20,2500,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-hydra-facial','Hydra Facial','Special',60,9900,'Active','Facial');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-hair-botox','Hair Botox','Special',180,17000,'Active','Hair treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-nano-plasty','Nano Plasty','Special',180,18000,'Active','Hair treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-eyebrows','Eyebrows','Threading',10,1200,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-upper-lip','Upper Lip','Threading',5,500,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-lower-lip','Lower Lip','Threading',5,300,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-chin','Chin','Threading',5,500,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-forehead','Forehead','Threading',10,500,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-neck','Neck','Threading',10,1000,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-threading-full-face','Full Face (Excluding Eyebrows)','Threading',20,2800,'Active','Facial Threading');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-eye-lash-tint','Eyelash Tint','Eye Treatments',20,1500,'Active','Lash Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-eyebrows-tint','Eyebrows Tint','Eye Treatments',10,1200,'Active','Brow treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-eyebrows-henna','Eyebrows Henna','Eye Treatments',30,3000,'Active','Brow treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-eyelash-lift','Eyelash Lift','Eye Treatments',30,4000,'Active','Lash Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-eyebrows','Eyebrows (Wax & Threading)','Waxing',15,1500,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-upper-lip','Upper Lip','Waxing',5,500,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-chin','Chin','Waxing',5,500,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-nose','Nose','Waxing',5,500,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-sides','Sides','Waxing',10,1000,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-cheeks','Cheeks','Waxing',10,1500,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-neck-line','Neck Line','Waxing',30,1000,'Active','Face Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-full-face','Full Face (Excluding Eyebrows)','Waxing',30,3500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-under-arms','Under Arms','Waxing',15,1000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-full-arms','Full Arms','Waxing',25,2500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-half-arms','Half Arms','Waxing',25,2000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-full-legs','Full Legs','Waxing',30,3500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-quarter-legs','Quarter Legs','Waxing',30,3000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-half-legs','Half Legs','Waxing',30,2500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-stomach','Stomach','Waxing',30,2000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-back','Back','Waxing',30,4000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-front','Front','Waxing',30,4000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-bikini-line','Bikini Line','Waxing',30,2500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-high-brazilian','High Brazilian','Waxing',30,3500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-brazilian','Brazilian','Waxing',30,4500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-buttocks','Buttocks','Waxing',20,2000,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-wax-lower-back','Lower Back','Waxing',20,3500,'Active','Body Waxing');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-fruit','Fruit Bleach','Beauty',30,3000,'Active','Face Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-gold','Gold Bleach','Beauty',30,3500,'Active','Face Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-diamond','Diamond Bleach','Beauty',30,3500,'Active','Face Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-neck','Neck Bleach','Beauty',30,2000,'Active','Face Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-full-arm','Full Arm','Beauty',30,4000,'Active','Body Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-full-back','Full Back','Beauty',30,6000,'Active','Body Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-bleach-full-front','Full Front','Beauty',45,6000,'Active','Body Bleach');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-cleansing','Cleansing','Beauty',20,2000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-cleansing-pack','Cleansing & Pack','Beauty',30,3000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-express-exfoliate','Express Exfoliate Facial','Beauty',35,5000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-normal','Normal Facial','Beauty',60,4500,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-dry-wrinkle','Dry / Wrinkle','Beauty',60,5000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-pimple-acne','Pimple / Acne','Beauty',60,5000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-pigmentation','Pigmentation Treatment','Beauty',60,5000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-fruit','Fruit Facial','Beauty',60,5000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-herbal','Herbal Facial','Beauty',60,5000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-gold','Gold Facial','Beauty',60,6000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-vitamin-c','Vitamin C','Beauty',70,7500,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-skin-glow','Skin Glow Facial','Beauty',70,7000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-diamond-glow','Diamond Glow Facial','Beauty',70,7500,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-advance-acne','Advance Acne','Beauty',70,7000,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-facial-sensitive-skin','Sensitive Skin','Beauty',70,6500,'Active','Facials');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-formal-hair','Formal Hairstyle (From)','Makeup & hairstyle',30,4500,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-formal-makeup','Formal Makeup (From)','Makeup & hairstyle',60,5500,'Active','Makeup');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-parents','Parents Makeup & Hairstyle (From)','Makeup & hairstyle',150,11000,'Active','Makeup & Hair');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-maternity','Maternity Makeup & Hairstyle (From)','Makeup & hairstyle',150,13000,'Active','Makeup & Hair');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-bridal','Bridal Package (From)','Makeup & hairstyle',180,26000,'Active','Makeup & Hair');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-party-attending','Party Attending Makeup & Hairstyle (From)','Makeup & hairstyle',150,14000,'Active','Makeup & Hair');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-style-party-host','Party Host','Makeup & hairstyle',120,18000,'Active','Makeup & Hair');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-trim-female','Just Trimming - Female (From)','Hair',30,3500,'Active','Cuts');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-trim-male','Just Trimming - Male (From)','Men',30,2000,'Active','Cuts');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-style-female','Style Cut - Female (From)','Hair',30,4500,'Active','Cuts');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-style-male','Style Cut - Male (From)','Men',30,2000,'Active','Cuts');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-blow-dry-female','Shampoo / Blow Dry - Female (From)','Hair',45,3000,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-blow-dry-male','Shampoo / Blow Dry - Male (From)','Men',45,1500,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-blow-wave-female','Shampoo / Blow Wave - Female (From)','Hair',60,4500,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-cut-blow-wave-male','Shampoo / Blow Wave - Male (From)','Men',60,3000,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-root-female','Root Color - Female (From)','Hair',60,4500,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-root-male','Root Color - Male (From)','Men',50,3500,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-full-female','Full Color - Female (From)','Hair',90,7000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-full-male','Full Color - Male (From)','Men',60,5000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-full-foils-female','Full Head Foils - Female (From)','Hair',150,14000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-full-foils-male','Full Head Foils - Male (From)','Men',90,10000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-half-foils-female','Half Head Foils - Female (From)','Hair',90,9000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-half-foils-male','Half Head Foils - Male (From)','Men',60,5000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-correction-female','Color Correction - Female (From)','Hair',90,6000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-correction-male','Color Correction - Male (From)','Men',90,4500,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-scalp-root-female','Scalp Bleach Root - Female (From)','Hair',120,9000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-scalp-root-male','Scalp Bleach Root - Male (From)','Men',90,7000,'Active','Hair color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-scalp-full-female','Scalp Bleach Full - Female (From)','Hair',120,18000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-scalp-full-male','Scalp Bleach Full - Male (From)','Men',90,13000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-face-framing-female','Face Framing - Female (From)','Hair',90,7000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-face-framing-male','Face Framing - Male (From)','Hair color',90,4000,'Active','General');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-toner-female','Toner - Female (From)','Hair',60,4500,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-toner-male','Toner - Male (From)','Men',50,3000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-creative-female','Creative Color - Female (From)','Hair',90,16000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-creative-male','Creative Color - Male (From)','Men',60,12000,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-balayage-full-female','Balayage Highlight Full - Female (From)','Hair',150,18500,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-color-ombre-female','Ombre - Female (From)','Hair',150,18500,'Active','Hair Color');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-protein-female','Protein - Female (From)','Hair',60,3500,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-protein-male','Protein - Male (From)','Men',50,2500,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-charcoal-female','Charcoal - Female (From)','Hair',60,5000,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-charcoal-male','Charcoal - Male (From)','Men',50,2500,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-oil-massage-female','Hair Oil Massage - Female (From)','Hair',30,3000,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-oil-massage-male','Hair Oil Massage - Male (From)','Men',30,2500,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-henna-female','Hair Henna - Female (From)','Hair',60,3500,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-treatment-henna-male','Hair Henna - Male (From)','Men',60,2500,'Active','Treatments');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-keratin-brazilian-female','Brazilian Keratin - Female (From)','Hair Smoothing Treatment',180,16000,'Active','Keratin');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-keratin-brazilian-male','Brazilian Keratin - Male (From)','Men',120,12000,'Active','Keratin');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-keratin-normal-female','Normal Keratin - Female (From)','Hair Smoothing Treatment',150,13000,'Active','Keratin');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-keratin-normal-male','Normal Keratin - Male (From)','Men',90,10000,'Active','Keratin');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-keratin-nanoplastia-female','Nanoplastia - Female (From)','Hair Smoothing Treatment',150,18000,'Active','Nanoplastia');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-keratin-nanoplastia-male','Nanoplastia - Male (From)','Men',120,13000,'Active','nanoplastia');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-permanent-straight-female','Hair Straight - Female (From)','Hair',235,18000,'Active','Permanent Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-permanent-straight-male','Hair Straight - Male (From)','Men',150,12000,'Active','Permanent Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-permanent-perming-female','Hair Perming - Female (From)','Hair',180,18000,'Active','Permanent Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-permanent-perming-male','Hair Perming - Male (From)','Men',120,12000,'Active','Permanent Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-temporary-iron-female','Hair Iron - Female (From)','Temporary',45,4000,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-temporary-iron-male','Hair Iron - Male (From)','Men',30,3000,'Active','Temporary Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-temporary-curl-female','Hair Curl - Female (From)','Temporary',45,4500,'Active','Styling');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-temporary-curl-male','Hair Curl - Male (From)','Men',30,3000,'Active','Temporary Treatment');
INSERT INTO "services" ("id","name","category","duration_minutes","price_cents","status","sub_category") VALUES('service-25a0ec34-1be0-4094-8d90-e946afa433d8','Keratin + Hair Cut','Special',90,19900,'Active','Hair treatment');
