CREATE TABLE IF NOT EXISTS branch_pos_sessions(token_hash TEXT PRIMARY KEY, branch_id TEXT NOT NULL, pin_hash TEXT NOT NULL, expires_at INTEGER NOT NULL);
ALTER TABLE sales ADD COLUMN recorded_by_id TEXT;
ALTER TABLE sales ADD COLUMN recorded_by_name TEXT;
ALTER TABLE sales ADD COLUMN cash_cents INTEGER;
ALTER TABLE sales ADD COLUMN card_cents INTEGER;
ALTER TABLE sales ADD COLUMN change_cents INTEGER;
ALTER TABLE sales ADD COLUMN edit_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE daily_closings ADD COLUMN closed_by_id TEXT;
ALTER TABLE daily_closings ADD COLUMN denomination_counts TEXT;
CREATE TABLE IF NOT EXISTS sale_edit_history(id TEXT PRIMARY KEY, sale_id TEXT NOT NULL, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, reason TEXT NOT NULL, before_json TEXT NOT NULL, after_json TEXT NOT NULL, created_at TEXT NOT NULL);
