-- Shared service catalogue. Services are global and available to every branch.
INSERT OR IGNORE INTO services (id, name, category, duration_minutes, price_cents, status) VALUES
  ('service-hydra-facial', 'Hydra Facial', 'Special for limited time', 60, 9900, 'Active'),
  ('service-hair-botox', 'Hair Botox', 'Special for limited time', 180, 17000, 'Active'),
  ('service-nano-plasty', 'Nano Plasty', 'Special for limited time', 180, 18000, 'Active'),
  ('service-threading-eyebrows', 'Eyebrows', 'Threading', 10, 1200, 'Active'),
  ('service-threading-upper-lip', 'Upper Lip', 'Threading', 5, 500, 'Active'),
  ('service-threading-lower-lip', 'Lower Lip', 'Threading', 5, 300, 'Active'),
  ('service-threading-chin', 'Chin', 'Threading', 5, 500, 'Active'),
  ('service-threading-forehead', 'Forehead', 'Threading', 10, 500, 'Active'),
  ('service-threading-neck', 'Neck', 'Threading', 10, 1000, 'Active'),
  ('service-threading-full-face', 'Full Face (Excluding Eyebrows)', 'Threading', 20, 2800, 'Active'),
  ('service-eye-lash-tint', 'Eyelash Tint', 'Eye treatment', 20, 1500, 'Active'),
  ('service-eyebrows-tint', 'Eyebrows Tint', 'Eye treatment', 10, 1200, 'Active'),
  ('service-eyebrows-henna', 'Eyebrows Henna', 'Eye treatment', 30, 3000, 'Active'),
  ('service-eyelash-lift', 'Eyelash Lift', 'Eye treatment', 30, 4000, 'Active'),
  ('service-wax-eyebrows', 'Eyebrows (Wax & Threading)', 'Waxing', 15, 1500, 'Active'),
  ('service-wax-upper-lip', 'Upper Lip', 'Waxing', 5, 500, 'Active'),
  ('service-wax-chin', 'Chin', 'Waxing', 5, 500, 'Active'),
  ('service-wax-nose', 'Nose', 'Waxing', 5, 500, 'Active'),
  ('service-wax-sides', 'Sides', 'Waxing', 10, 1000, 'Active'),
  ('service-wax-cheeks', 'Cheeks', 'Waxing', 10, 1500, 'Active'),
  ('service-wax-neck-line', 'Neck Line', 'Waxing', 30, 1000, 'Active'),
  ('service-wax-full-face', 'Full Face (Excluding Eyebrows)', 'Waxing', 30, 3500, 'Active'),
  ('service-wax-under-arms', 'Under Arms', 'Waxing', 15, 1000, 'Active'),
  ('service-wax-full-arms', 'Full Arms', 'Waxing', 25, 2500, 'Active'),
  ('service-wax-half-arms', 'Half Arms', 'Waxing', 25, 2000, 'Active'),
  ('service-wax-full-legs', 'Full Legs', 'Waxing', 30, 3500, 'Active'),
  ('service-wax-quarter-legs', 'Quarter Legs', 'Waxing', 30, 3000, 'Active'),
  ('service-wax-half-legs', 'Half Legs', 'Waxing', 30, 2500, 'Active'),
  ('service-wax-stomach', 'Stomach', 'Waxing', 30, 2000, 'Active'),
  ('service-wax-back', 'Back', 'Waxing', 30, 4000, 'Active'),
  ('service-wax-front', 'Front', 'Waxing', 30, 4000, 'Active'),
  ('service-wax-bikini-line', 'Bikini Line', 'Waxing', 30, 2500, 'Active'),
  ('service-wax-high-brazilian', 'High Brazilian', 'Waxing', 30, 3500, 'Active'),
  ('service-wax-brazilian', 'Brazilian', 'Waxing', 30, 4500, 'Active'),
  ('service-wax-buttocks', 'Buttocks', 'Waxing', 20, 2000, 'Active'),
  ('service-wax-lower-back', 'Lower Back', 'Waxing', 20, 3500, 'Active'),
  ('service-bleach-fruit', 'Fruit Bleach', 'Bleach', 30, 3000, 'Active'),
  ('service-bleach-gold', 'Gold Bleach', 'Bleach', 30, 3500, 'Active'),
  ('service-bleach-diamond', 'Diamond Bleach', 'Bleach', 30, 3500, 'Active'),
  ('service-bleach-neck', 'Neck Bleach', 'Bleach', 30, 2000, 'Active'),
  ('service-bleach-full-arm', 'Full Arm', 'Bleach', 30, 4000, 'Active'),
  ('service-bleach-full-back', 'Full Back', 'Bleach', 30, 6000, 'Active'),
  ('service-bleach-full-front', 'Full Front', 'Bleach', 45, 6000, 'Active'),
  ('service-facial-cleansing', 'Cleansing', 'Facial', 20, 2000, 'Active'),
  ('service-facial-cleansing-pack', 'Cleansing & Pack', 'Facial', 30, 3000, 'Active'),
  ('service-facial-express-exfoliate', 'Express Exfoliate Facial', 'Facial', 35, 5000, 'Active'),
  ('service-facial-normal', 'Normal Facial', 'Facial', 60, 4500, 'Active'),
  ('service-facial-dry-wrinkle', 'Dry / Wrinkle', 'Facial', 60, 5000, 'Active'),
  ('service-facial-pimple-acne', 'Pimple / Acne', 'Facial', 60, 5000, 'Active'),
  ('service-facial-pigmentation', 'Pigmentation Treatment', 'Facial', 60, 5000, 'Active'),
  ('service-facial-fruit', 'Fruit Facial', 'Facial', 60, 5000, 'Active'),
  ('service-facial-herbal', 'Herbal Facial', 'Facial', 60, 5000, 'Active'),
  ('service-facial-gold', 'Gold Facial', 'Facial', 60, 6000, 'Active'),
  ('service-facial-vitamin-c', 'Vitamin C', 'Facial', 70, 7500, 'Active'),
  ('service-facial-skin-glow', 'Skin Glow Facial', 'Facial', 70, 7000, 'Active'),
  ('service-facial-diamond-glow', 'Diamond Glow Facial', 'Facial', 70, 7500, 'Active'),
  ('service-facial-advance-acne', 'Advance Acne', 'Facial', 70, 7000, 'Active'),
  ('service-facial-sensitive-skin', 'Sensitive Skin', 'Facial', 70, 6500, 'Active'),
  ('service-style-formal-hair', 'Formal Hairstyle (From)', 'Makeup & hairstyle', 30, 4500, 'Active'),
  ('service-style-formal-makeup', 'Formal Makeup (From)', 'Makeup & hairstyle', 60, 5500, 'Active'),
  ('service-style-parents', 'Parents Makeup & Hairstyle (From)', 'Makeup & hairstyle', 150, 11000, 'Active'),
  ('service-style-maternity', 'Maternity Makeup & Hairstyle (From)', 'Makeup & hairstyle', 150, 13000, 'Active'),
  ('service-style-bridal', 'Bridal Package (From)', 'Makeup & hairstyle', 180, 26000, 'Active'),
  ('service-style-party-attending', 'Party Attending Makeup & Hairstyle (From)', 'Makeup & hairstyle', 150, 14000, 'Active'),
  ('service-style-party-host', 'Party Host', 'Makeup & hairstyle', 120, 18000, 'Active'),
  ('service-cut-trim-female', 'Just Trimming - Female (From)', 'Hair cut', 30, 3500, 'Active'),
  ('service-cut-trim-male', 'Just Trimming - Male (From)', 'Hair cut', 30, 2000, 'Active'),
  ('service-cut-style-female', 'Style Cut - Female (From)', 'Hair cut', 30, 4500, 'Active'),
  ('service-cut-style-male', 'Style Cut - Male (From)', 'Hair cut', 30, 2000, 'Active'),
  ('service-cut-blow-dry-female', 'Shampoo / Blow Dry - Female (From)', 'Hair cut', 45, 3000, 'Active'),
  ('service-cut-blow-dry-male', 'Shampoo / Blow Dry - Male (From)', 'Hair cut', 45, 1500, 'Active'),
  ('service-cut-blow-wave-female', 'Shampoo / Blow Wave - Female (From)', 'Hair cut', 60, 4500, 'Active'),
  ('service-cut-blow-wave-male', 'Shampoo / Blow Wave - Male (From)', 'Hair cut', 60, 3000, 'Active'),
  ('service-color-root-female', 'Root Color - Female (From)', 'Hair color', 60, 4500, 'Active'),
  ('service-color-root-male', 'Root Color - Male (From)', 'Hair color', 50, 3500, 'Active'),
  ('service-color-full-female', 'Full Color - Female (From)', 'Hair color', 90, 7000, 'Active'),
  ('service-color-full-male', 'Full Color - Male (From)', 'Hair color', 60, 5000, 'Active'),
  ('service-color-full-foils-female', 'Full Head Foils - Female (From)', 'Hair color', 150, 14000, 'Active'),
  ('service-color-full-foils-male', 'Full Head Foils - Male (From)', 'Hair color', 90, 10000, 'Active'),
  ('service-color-half-foils-female', 'Half Head Foils - Female (From)', 'Hair color', 90, 9000, 'Active'),
  ('service-color-half-foils-male', 'Half Head Foils - Male (From)', 'Hair color', 60, 5000, 'Active'),
  ('service-color-correction-female', 'Color Correction - Female (From)', 'Hair color', 90, 6000, 'Active'),
  ('service-color-correction-male', 'Color Correction - Male (From)', 'Hair color', 90, 4500, 'Active'),
  ('service-color-scalp-root-female', 'Scalp Bleach Root - Female (From)', 'Hair color', 120, 9000, 'Active'),
  ('service-color-scalp-root-male', 'Scalp Bleach Root - Male (From)', 'Hair color', 90, 7000, 'Active'),
  ('service-color-scalp-full-female', 'Scalp Bleach Full - Female (From)', 'Hair color', 120, 18000, 'Active'),
  ('service-color-scalp-full-male', 'Scalp Bleach Full - Male (From)', 'Hair color', 90, 13000, 'Active'),
  ('service-color-face-framing-female', 'Face Framing - Female (From)', 'Hair color', 90, 7000, 'Active'),
  ('service-color-face-framing-male', 'Face Framing - Male (From)', 'Hair color', 90, 4000, 'Active'),
  ('service-color-toner-female', 'Toner - Female (From)', 'Hair color', 60, 4500, 'Active'),
  ('service-color-toner-male', 'Toner - Male (From)', 'Hair color', 50, 3000, 'Active'),
  ('service-color-creative-female', 'Creative Color - Female (From)', 'Hair color', 90, 16000, 'Active'),
  ('service-color-creative-male', 'Creative Color - Male (From)', 'Hair color', 60, 12000, 'Active'),
  ('service-color-balayage-full-female', 'Balayage Highlight Full - Female (From)', 'Hair color', 150, 18500, 'Active'),
  ('service-color-ombre-female', 'Ombre - Female (From)', 'Hair color', 150, 18500, 'Active'),
  ('service-treatment-protein-female', 'Protein - Female (From)', 'Treatment', 60, 3500, 'Active'),
  ('service-treatment-protein-male', 'Protein - Male (From)', 'Treatment', 50, 2500, 'Active'),
  ('service-treatment-charcoal-female', 'Charcoal - Female (From)', 'Treatment', 60, 5000, 'Active'),
  ('service-treatment-charcoal-male', 'Charcoal - Male (From)', 'Treatment', 50, 2500, 'Active'),
  ('service-treatment-oil-massage-female', 'Hair Oil Massage - Female (From)', 'Treatment', 30, 3000, 'Active'),
  ('service-treatment-oil-massage-male', 'Hair Oil Massage - Male (From)', 'Treatment', 30, 2500, 'Active'),
  ('service-treatment-henna-female', 'Hair Henna - Female (From)', 'Treatment', 60, 3500, 'Active'),
  ('service-treatment-henna-male', 'Hair Henna - Male (From)', 'Treatment', 60, 2500, 'Active'),
  ('service-keratin-brazilian-female', 'Brazilian Keratin - Female (From)', 'Keratin', 180, 16000, 'Active'),
  ('service-keratin-brazilian-male', 'Brazilian Keratin - Male (From)', 'Keratin', 120, 12000, 'Active'),
  ('service-keratin-normal-female', 'Normal Keratin - Female (From)', 'Keratin', 150, 13000, 'Active'),
  ('service-keratin-normal-male', 'Normal Keratin - Male (From)', 'Keratin', 90, 10000, 'Active'),
  ('service-keratin-nanoplastia-female', 'Nanoplastia - Female (From)', 'Keratin', 150, 18000, 'Active'),
  ('service-keratin-nanoplastia-male', 'Nanoplastia - Male (From)', 'Keratin', 120, 13000, 'Active'),
  ('service-permanent-straight-female', 'Hair Straight - Female (From)', 'Permanent', 235, 18000, 'Active'),
  ('service-permanent-straight-male', 'Hair Straight - Male (From)', 'Permanent', 150, 12000, 'Active'),
  ('service-permanent-perming-female', 'Hair Perming - Female (From)', 'Permanent', 180, 18000, 'Active'),
  ('service-permanent-perming-male', 'Hair Perming - Male (From)', 'Permanent', 120, 12000, 'Active'),
  ('service-temporary-iron-female', 'Hair Iron - Female (From)', 'Temporary', 45, 4000, 'Active'),
  ('service-temporary-iron-male', 'Hair Iron - Male (From)', 'Temporary', 30, 3000, 'Active'),
  ('service-temporary-curl-female', 'Hair Curl - Female (From)', 'Temporary', 45, 4500, 'Active'),
  ('service-temporary-curl-male', 'Hair Curl - Male (From)', 'Temporary', 30, 3000, 'Active');
