DELETE FROM services;
DELETE FROM service_category_order;
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-advance-acne','Advance Acne','Beauty','Facials',70,7000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial','Beauty facial','Beauty','Facials',60,9500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-cleansing','Cleansing','Beauty','Facials',20,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-cleansing-pack','Cleansing & Pack','Beauty','Facials',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-diamond','Diamond Bleach','Beauty','Face Bleach',30,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-diamond-glow','Diamond Glow Facial','Beauty','Facials',70,7500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-dry-wrinkle','Dry / Wrinkle','Beauty','Facials',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-express-exfoliate','Express Exfoliate Facial','Beauty','Facials',35,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-fruit','Fruit Bleach','Beauty','Face Bleach',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-fruit','Fruit Facial','Beauty','Facials',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-full-arm','Full Arm','Beauty','Body Bleach',30,4000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-full-back','Full Back','Beauty','Body Bleach',30,6000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-full-front','Full Front','Beauty','Body Bleach',45,6000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-gold','Gold Bleach','Beauty','Face Bleach',30,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-gold','Gold Facial','Beauty','Facials',60,6000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-herbal','Herbal Facial','Beauty','Facials',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-bleach-neck','Neck Bleach','Beauty','Face Bleach',30,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-normal','Normal Facial','Beauty','Facials',60,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-pigmentation','Pigmentation Treatment','Beauty','Facials',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-pimple-acne','Pimple / Acne','Beauty','Facials',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-sensitive-skin','Sensitive Skin','Beauty','Facials',70,6500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-skin-glow','Skin Glow Facial','Beauty','Facials',70,7000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-facial-vitamin-c','Vitamin C','Beauty','Facials',70,7500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-eyebrows-henna','Eyebrows Henna','Eye Treatments','Brow treatment',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-eyebrows-tint','Eyebrows Tint','Eye Treatments','Brow treatment',10,1200,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-eyelash-lift','Eyelash Lift','Eye Treatments','Lash Treatment',30,4000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-eye-lash-tint','Eyelash Tint','Eye Treatments','Lash Treatment',20,1500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-blowdry','Blow dry','Hair','Styling',35,5500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-charcoal-female','Charcoal - Female (From)','Hair','Treatments',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-correction-female','Color Correction - Female (From)','Hair','Hair Color',90,6000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-colour','Colour service','Hair','Hair Color',90,12000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-creative-female','Creative Color - Female (From)','Hair','Hair Color',90,16000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-face-framing-female','Face Framing - Female (From)','Hair','Hair Color',90,7000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-henna-female','Hair Henna - Female (From)','Hair','Treatments',60,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-oil-massage-female','Hair Oil Massage - Female (From)','Hair','Treatments',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-permanent-perming-female','Hair Perming - Female (From)','Hair','Permanent Treatment',180,18000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-permanent-straight-female','Hair Straight - Female (From)','Hair','Permanent Treatment',235,18000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment','Hair treatment','Hair','Treatments',45,7000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-haircut','Haircut','Hair','Cuts',30,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-half-foils-female','Half Head Foils - Female (From)','Hair','Hair Color',90,9000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-trim-female','Just Trimming - Female (From)','Hair','Cuts',30,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-ombre-female','Ombre - Female (From)','Hair','Hair Color',150,18500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-protein-female','Protein - Female (From)','Hair','Treatments',60,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-root-female','Root Color - Female (From)','Hair','Hair Color',60,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-scalp-full-female','Scalp Bleach Full - Female (From)','Hair','Hair Color',120,18000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-scalp-root-female','Scalp Bleach Root - Female (From)','Hair','Hair Color',120,9000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-blow-dry-female','Shampoo / Blow Dry - Female (From)','Hair','Styling',45,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-balayage-full-female','Balayage Highlight Full - Female (From)','Hair','Hair Color',150,18500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-full-female','Full Color - Female (From)','Hair','Hair Color',90,7000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-full-foils-female','Full Head Foils - Female (From)','Hair','Hair Color',150,14000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-blow-wave-female','Shampoo / Blow Wave - Female (From)','Hair','Styling',60,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-style-female','Style Cut - Female (From)','Hair','Cuts',30,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-toner-female','Toner - Female (From)','Hair','Hair Color',60,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-keratin-brazilian-female','Brazilian Keratin - Female (From)','Hair Smoothing Treatment','Keratin',180,16000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-keratin-nanoplastia-female','Nanoplastia - Female (From)','Hair Smoothing Treatment','Nanoplastia',150,18000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-keratin-normal-female','Normal Keratin - Female (From)','Hair Smoothing Treatment','Keratin',150,13000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-bridal','Bridal Package (From)','Makeup & hairstyle','Makeup & Hair',180,26000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-formal-hair','Formal Hairstyle (From)','Makeup & hairstyle','Styling',30,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-formal-makeup','Formal Makeup (From)','Makeup & hairstyle','Makeup',60,5500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-maternity','Maternity Makeup & Hairstyle (From)','Makeup & hairstyle','Makeup & Hair',150,13000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-parents','Parents Makeup & Hairstyle (From)','Makeup & hairstyle','Makeup & Hair',150,11000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-party-attending','Party Attending Makeup & Hairstyle (From)','Makeup & hairstyle','Makeup & Hair',150,14000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-style-party-host','Party Host','Makeup & hairstyle','Makeup & Hair',120,18000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-keratin-brazilian-male','Brazilian Keratin - Male (From)','Men','Keratin',120,12000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-charcoal-male','Charcoal - Male (From)','Men','Treatments',50,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-correction-male','Color Correction - Male (From)','Men','Hair Color',90,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-creative-male','Creative Color - Male (From)','Men','Hair Color',60,12000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-full-male','Full Color - Male (From)','Men','Hair Color',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-full-foils-male','Full Head Foils - Male (From)','Men','Hair Color',90,10000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-temporary-curl-male','Hair Curl - Male (From)','Men','Temporary Treatment',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-henna-male','Hair Henna - Male (From)','Men','Treatments',60,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-temporary-iron-male','Hair Iron - Male (From)','Men','Temporary Treatment',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-oil-massage-male','Hair Oil Massage - Male (From)','Men','Treatments',30,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-permanent-perming-male','Hair Perming - Male (From)','Men','Permanent Treatment',120,12000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-permanent-straight-male','Hair Straight - Male (From)','Men','Permanent Treatment',150,12000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-half-foils-male','Half Head Foils - Male (From)','Men','Hair Color',60,5000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-trim-male','Just Trimming - Male (From)','Men','Cuts',30,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-keratin-nanoplastia-male','Nanoplastia - Male (From)','Men','nanoplastia',120,13000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-keratin-normal-male','Normal Keratin - Male (From)','Men','Keratin',90,10000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-treatment-protein-male','Protein - Male (From)','Men','Treatments',50,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-root-male','Root Color - Male (From)','Men','Hair Color',50,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-scalp-full-male','Scalp Bleach Full - Male (From)','Men','Hair Color',90,13000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-scalp-root-male','Scalp Bleach Root - Male (From)','Men','Hair color',90,7000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-blow-dry-male','Shampoo / Blow Dry - Male (From)','Men','Styling',45,1500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-blow-wave-male','Shampoo / Blow Wave - Male (From)','Men','Styling',60,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-cut-style-male','Style Cut - Male (From)','Men','Cuts',30,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-color-toner-male','Toner - Male (From)','Men','Hair Color',50,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-hair-botox','Hair Botox','Special','Hair treatment',180,17000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-hydra-facial','Hydra Facial','Special','Facial',60,9900,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-25a0ec34-1be0-4094-8d90-e946afa433d8','Keratin + Hair Cut','Special','Hair treatment',90,19900,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-nano-plasty','Nano Plasty','Special','Hair treatment',180,18000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-temporary-curl-female','Hair Curl - Female (From)','Temporary','Styling',45,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-temporary-iron-female','Hair Iron - Female (From)','Temporary','Styling',45,4000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-chin','Chin','Threading','Facial Threading',5,500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading','Eye Brow Threading','Threading','Facial Threading',20,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-eyebrows','Eyebrows','Threading','Facial Threading',10,1200,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-forehead','Forehead','Threading','Facial Threading',10,500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-full-face','Full Face (Excluding Eyebrows)','Threading','Facial Threading',20,2800,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-lower-lip','Lower Lip','Threading','Facial Threading',5,300,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-neck','Neck','Threading','Facial Threading',10,1000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-threading-upper-lip','Upper Lip','Threading','Facial Threading',5,500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-back','Back','Waxing','Body Waxing',30,4000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-bikini-line','Bikini Line','Waxing','Body Waxing',30,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-brazilian','Brazilian','Waxing','Body Waxing',30,4500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-buttocks','Buttocks','Waxing','Body Waxing',20,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-cheeks','Cheeks','Waxing','Face Waxing',10,1500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-chin','Chin','Waxing','Face Waxing',5,500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-eyebrows','Eyebrows (Wax & Threading)','Waxing','Face Waxing',15,1500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-front','Front','Waxing','Body Waxing',30,4000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-full-arms','Full Arms','Waxing','Body Waxing',25,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-full-face','Full Face (Excluding Eyebrows)','Waxing','Body Waxing',30,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-full-legs','Full Legs','Waxing','Body Waxing',30,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-half-arms','Half Arms','Waxing','Body Waxing',25,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-half-legs','Half Legs','Waxing','Body Waxing',30,2500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-high-brazilian','High Brazilian','Waxing','Body Waxing',30,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-lower-back','Lower Back','Waxing','Body Waxing',20,3500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-neck-line','Neck Line','Waxing','Face Waxing',30,1000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-nose','Nose','Waxing','Face Waxing',5,500,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-quarter-legs','Quarter Legs','Waxing','Body Waxing',30,3000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-sides','Sides','Waxing','Face Waxing',10,1000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-stomach','Stomach','Waxing','Body Waxing',30,2000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-under-arms','Under Arms','Waxing','Body Waxing',15,1000,'Active');
INSERT INTO services (id,name,category,sub_category,duration_minutes,price_cents,status) VALUES ('service-wax-upper-lip','Upper Lip','Waxing','Face Waxing',5,500,'Active');
